// Generated by https://pagedraw.io/pages/13542
import React from 'react';
import './aboutframe.css';


export default class Aboutframe extends React.Component {
  render() {
    return (
      <div className="aboutframe-aboutframe-0">
          <div className="aboutframe-0">
              <div className="aboutframe-0-0">
                  <div className="aboutframe-0-0-0">
                      <div className="aboutframe-about_us_-4">About Us</div>
                  </div>
                  <div className="aboutframe-0-0-1">
                      <div className="aboutframe-fairfield_county_animal_shelter_is_a_no_kill_shelter_that_is_affiliated_with_fairfield_county_animal_control_and_is_located_in_winnsboro_south_carolina_-1">
                          Fairfield County Animal Shelter is a no kill shelter that is affiliated with Fairfield County Animal Control and is located in Winnsboro, South Carolina.
                      </div>
                  </div>
                  <div className="aboutframe-0-0-2">
                      <div className="aboutframe-hours_-0">{"Hours:"}</div>
                  </div>
                  <div className="aboutframe-0-0-3">
                      <div className="aboutframe-monday_-_friday_1">
                          <div>{"Monday - Friday 12:00 PM - 4:30 PM"}</div>
                          <br/>
                          <div>{"Saturday: Appointment Only"}</div>
                      </div>
                  </div>
              </div>
              <div className="aboutframe-0-1">
                  <div className="aboutframe-0-1-0">
                      <div className="aboutframe-0-1-0-0">
                          <div className="aboutframe-rectangle-2">
                              <div className="aboutframe-0-1-0-0-0-0">
                               <a href="https://www.petfinder.com/member/us/sc/winnsboro/fairfield-county-animal-adoption-center-sc209/" target="_blank">
                                  <img src="https://ucarecdn.com/e4daf0d3-5ce4-4167-aae7-9ec1b3c61fef/" className="aboutframe-image-6" /> 
                                  </a>
                              </div>
                          </div>
                          <div className="aboutframe-available_pets_-5">
                              Find available pets at
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="aboutframe-1">
              <div className="aboutframe-mission_-3">Mission</div>
          </div>
          <div className="aboutframe-2">
              <div className="aboutframe-the_mission_of_fairfield_animal_shelter_is_to_provide_a_safe_and_humane_facility_for_those_animals_that_are_stray_or_unwanted_and_to_minimize_the_number_of_euthanized_animals_annually_to_educate_the_public_on_responsible_pet_ownership_such_as_spaying_and_neutering_and_welcome_relationships_with_legitimate_animal_rescue_organizations_that_wish_to_work_with_us_all_activities_shall_be_in_compliance_with_federal_state_and_local_laws_and_regulations_and_performed_by_a_humane_and_professional_staff_-4">
                  The mission of Fairfield Animal Shelter is to provide a safe and humane facility for those animals that are stray or unwanted, and to minimize the number of euthanized animals annually, to educate the public on responsible pet ownership such as spaying and neutering, and welcome relationships with legitimate animal rescue organizations that wish to work with us. All activities shall be in compliance with Federal, State and local laws and regulations and performed by a humane and professional staff.
              </div>
          </div>
          <div className="aboutframe-3">
              <div className="aboutframe-adoption_fee_-8">
                  {"Adoption Fee:"}
              </div>
          </div>
          <div className="aboutframe-4">
              <div className="aboutframe-4-0">
                  <div className="aboutframe-4-0-0">
                      <div className="aboutframe-dogs_puppies_8">
                          <div>{"Dogs/Puppies: $80.00"}</div>
                          <br/>
                          <div>{"Cats/Kittens:  $40.00"}</div>
                      </div>
                  </div>
              </div>
              <div className="aboutframe-4-1">
                  <div className="aboutframe-4-1-0">
                      <div className="adoptframe-AdoptionApplication">
                       <a href="http://www.fairfieldsc.com/_fileUploads/adoption%20application%202.pdf" target="_blank">
                     
                       Get Adoption Application Here.</a>  
                      </div>
                  </div>
              </div>
          </div>
          <div className="aboutframe-5">
              <div className="aboutframe-_adoption_fees_are_per_animal_an_adoption_application_must_be_completed_and_approved_before_anyone_is_allowed_to_adopt_an_animal_from_our_facility_a_home_visit_reference_and_a_vet_check_may_be_required_before_an_application_is_approved_-7">
                  <br/>
                  <br/>
                  <div>Adoption fees are per animal.  An Adoption Application must be completed and approved before anyone is allowed to adopt an animal from our facility. </div>
                  <br/>
                  <div>A home visit, reference and a vet check may be required before an application is approved</div>
                  <div> </div>
              </div>
          </div>
          <div className="aboutframe-6">
              <div className="aboutframe-all_fees_are_non-refundable_-7">
                  All fees are non-refundable
              </div>
          </div>
      </div>
    );
  }
};
