// Generated by https://pagedraw.io/pages/13542
import React from 'react';
import './component_2.css';


export default class Component_2 extends React.Component {
  render() {
    return (
      <div className="component_2-component_2" /> 
    );
  }
};
