// Generated by https://pagedraw.io/pages/13542
import React from 'react';
import './component_1.css';


export default class Component_1 extends React.Component {
  render() {
    return (
      <div className="component_1-component_1" /> 
    );
  }
};
