// Generated by https://pagedraw.io/pages/13530
import React from 'react';
import './contactframe.css';


export default class Contactframe extends React.Component {
  render() {
    return (
      <div className="contactframe-contactframe-9">
          <div className="contactframe-0">
              <div className="contactframe-0-0">
                  <div className="contactframe-0-0-0">
                      <div className="contactframe-rectangle-9">
                          <div className="contactframe-0-0-0-0-0">
                              <div className="contactframe-contact_us_-9">
                                  Contact Us
                              </div>
                          </div>
                          <div className="contactframe-0-0-0-0-1">
                              <div className="contactframe-call_us_at_-7">
                                  {"Call us at:"}
                              </div>
                          </div>
                          <div className="contactframe-0-0-0-0-2">
                              <div className="contactframe-_8">{"(803) 815-0805"}</div>
                          </div>
                          <div className="contactframe-0-0-0-0-3">
                              <div className="contactframe-visit_us_at_-1">
                                  {"Visit us at:"}
                              </div>
                          </div>
                          <div className="contactframe-0-0-0-0-4">
                              <div className="contactframe-1">
                                  <div>1678 Hwy 321 Business North</div>
                                  <div>Winnsboro, SC 29180</div>
                              </div>
                          </div>
                          <div className="contactframe-0-0-0-0-5">
                              <div className="contactframe-send_a_letter_or_package_to_-1">
                                  {"Send a letter or package to:"}
                              </div>
                          </div>
                          <div className="contactframe-0-0-0-0-6">
                              <div className="contactframe-animal_adoption_center_po_box_6">
                                  <div>Animal Adoption Center</div>
                                  <div>PO Box 60</div>
                                  <div>Winnsboro, SC 29180</div>
                              </div>
                          </div>
                          <div className="contactframe-0-0-0-0-7">
                              <div className="contactframe-0-0-0-0-7-0">
                                  <div className="contactframe-0-0-0-0-7-0-0">
                                      <div className="contactframe-0-0-0-0-7-0-0-0">
                                          <div className="contactframe-you_can_also_-4">
                                              You can also 
                                          </div>
                                          <div className="contactframe-email_us_-9">
                                         
                                          <a href= "mailto:bob.innes@fairfield.sc.gov"> <font size = "5">email us!</font></a></div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="contactframe-0-1">
                  <div className="contactframe-0-1-0">
                      <div className="contactframe-0-1-0-0">
                          <div className="contactframe-rectangle_2" /> 
                          <a href= "https://www.google.com/maps/dir/34.2301988,-81.7400433/winnsboro+county+adoption+center/@34.3175735,-81.7005932,10z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x8856171e8df59bbf:0xf81845782d31f3f0!2m2!1d-81.1019155!2d34.3997382"
                          target="_blank">
                          <img src="https://ucarecdn.com/1afed947-8fce-4417-ae79-70b35d3a0151/" className="contactframe-image-8" /> 
                          </a>
                          
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
