// Generated by https://pagedraw.io/pages/13524
import React from 'react';
import './frame.css';


export default class Frame extends React.Component {
  render() {
    return (
      <div className="frame-frame-0">
          <div className="frame-0">
              <div className="frame-rectangle_6">
                  <div className="frame-0-0-0">
                      <div className="frame-0-0-0-0">
                          <div className="frame-rectangle_2">
                              <div className="frame-0-0-0-0-0-0">
                                  <div className="frame-email_bob_innes_fairfield_sc_gov-0">
                                      {"Email: bob.innes@fairfield.sc.gov"}
                                  </div>
                              </div>
                          </div>
                          <div className="frame-fairfield_county_animal_shelter-0">
                              Fairfield County Animal Shelter
                          </div>
                          <div className="frame-2">
                              2065 US-321 BYP, Winnsboro, SC 29180
                          </div>
                          <div className="frame-_8">{"(803) 635-9944"}</div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="frame-1">
              <div className="frame-1-0">
                  <div className="frame-1-0-0">
                      <div className="frame-join_us-0">Join Us</div>
                  </div>
                  <div className="frame-1-0-1">
                      <div className="frame-1-0-1-0">
                          <div className="frame-1-0-1-0-0">
                              <div className="frame-1-0-1-0-0-0">
                                  <div className="frame-rectangle_6-0" /> 
                                  <a href="https://www.facebook.com/FCAAC/" target="_blank">
                                  <img src="https://ucarecdn.com/26de0c52-999e-4eab-bee9-42ffb86d220d/" className="frame-image_2" /> 
                                  </a>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="frame-rectangle_4">
                  <div className="frame-1-1-0">
                      <div className="frame-pet_of_the_week_-0">
                          Pet of the Week!
                      </div>
                  </div>
                  <div className="frame-1-1-1">
                      <div className="frame-rectangle_6-00">
                          <div className="frame-1-1-1-0-0">
                              <div className="frame-image_4">
                                  <div className="frame-1-1-1-0-0-0-0">
                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/88f2/ec00/8fb517057a247baccdac46da9d7aa374" className="frame-image-7" /> 
                                  </div>
                              </div>
                          </div>
                          <div className="frame-1-1-1-0-1">
                              <div className="frame-baxter-0">Baxter</div>
                          </div>
                          <div className="frame-1-1-1-0-2">
                              <div className="frame-baxter_s_purr_will_soothe_even_the_most_savage_beast_baxter_s_hobbies_are_snuggling_eating_and_sleeping_baxter_gets_along_well_with_other_cats_and_dogs_and_is_the_most_lovable_soul_you_will_ever_meet_will_you_be_his_forever_home_-0">
                                  <div>{"Baxter’s purr will soothe even the most savage beast.  Baxter’s hobbies are:"}</div>
                                  <div>snuggling, eating and sleeping.</div>
                                  <div>Baxter gets along well with other cats and dogs and is the most lovable soul you will ever meet.</div>
                                  <div>{"Will you be his forever home?"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="frame-1-2">
                  <div className="frame-1-2-0">
                     
                      <img src="https://ucarecdn.com/cd22add8-2a65-46a2-9213-eb8d0d4c6650/" className="frame-image_3" /> 
                     
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
