// Generated by https://pagedraw.io/pages/13555
import React from 'react';
import './helpframe.css';


export default class Helpframe extends React.Component {
  render() {
    return (
      <div className="helpframe-helpframe-5">
          <div className="helpframe-0">
              <div className="helpframe-0-0">
                  <div className="helpframe-0-0-0">
                      <div className="helpframe-you_can_help_-5">
                          You Can Help!
                      </div>
                  </div>
                  <div className="helpframe-0-0-1">
                      <div className="helpframe-some_ways_you_can_volunteer_-0">
                          Some ways you can volunteer
                      </div>
                  </div>
                  <div className="helpframe-0-0-2">
                      <div className="helpframe-to_volunteer_you_must_be_at_least_1">
                          To volunteer you must be at least 16 years old
                      </div>
                  </div>
                  <div className="helpframe-0-0-3">
                      <div className="helpframe-_dog_and_cat_socialization_dog_walkers_cat_room_attendant_kennel_cleaning_transport_administrative_and_clerical_foster_-5">
                          <div>   Dog and cat socialization</div>
                          <br/>
                          <div>   Dog walkers</div>
                          <br/>
                          <div>   Cat room attendant</div>
                          <br/>
                          <div>   Kennel Cleaning</div>
                          <br/>
                          <div>   Transport</div>
                          <br/>
                          <div>   Administrative and clerical </div>
                          <br/>
                          <div>   Foster</div>
                      </div>
                  </div>
              </div>
              <div className="helpframe-0-1">
                  <div className="helpframe-0-1-0">
                      <div className="helpframe-rectangle_3">
                          <div className="helpframe-0-1-0-0-0">
                              <div className="helpframe-the_following_are_always_in_need_-4">
                                  The following are ALWAYS in need!
                              </div>
                          </div>
                          <div className="helpframe-0-1-0-0-1">
                              <div className="helpframe-_trash_bags_3">
                              <ul>
                                              <li>Trash bags – 30 gallon &amp; kitchen</li>         
                                              <li>Paper towels &amp; toilet paper</li>
                                              <li>Canned dog &amp; cat food – any brand</li>
                                              <li>All sizes of dog collars</li>
                                              <li>Dawn Dish detergent (only)</li>
                                              <li>Liquid laundry detergen</li>
                                              <li>Antibacterial soap</li>
                                              <li>Postage stamps</li>
                                              
                                              </ul>

                              </div>
                              <div className="helpframe-_copy_colored_paper_bleach_collapsible_dog_crates_plastic_cat_carriers_toys_for_dogs_and_cats_news_papers_batteries_aa_aaa_gift_cards_sheets_-4">
                              <ul>
                                                  <li>Copy &amp;colored paper</li>
                                                  <li>Bleach</li>
                                                  <li>Collapsible dog crates</li>
                                                  <li>Plastic cat carriers</li>
                                                  <li>Toys for dogs &amp; cats</li>
                                                  <li>News papers</li>
                                                  <li>Batteries – AA &amp; AAA</li>
                                                  <li>Gift Cards</li>
                                                  <li>Sheets</li>
                                                  </ul>

                              </div>
                          </div>
                          <div className="helpframe-0-1-0-0-2">
                              <div className="helpframe-rectangle_4">
                                  <div className="helpframe-0-1-0-0-2-0-0">
                                  <a href="https://www.paypal.com/us/home" target="_blank">
                                    <img src="https://ucarecdn.com/46886cb9-f35b-4518-a572-d0ac882b2f75/" className="helpframe-image_2" /> 
                                  </a>
                                  </div>
                              </div>
                              <div className="helpframe-0-1-0-0-2-1">
                                  <div className="helpframe-0-1-0-0-2-1-0">
                                      <div className="helpframe-rectangle-5">
                                          <div className="helpframe-0-1-0-0-2-1-0-0-0">
                                          <a href="https://www.amazon.com/gp/registry/wishlist/YI9KQRZZ0394" target="_blank">
                                    
                                              <img src="https://ucarecdn.com/f2f8c527-bc8f-4984-8e75-f1ec3b00ed3b/" className="helpframe-image-3" /> 
                                              </a>
                                              </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="helpframe-0-1-0-0-3">
                              <div className="helpframe-bring_donations_to_our_shelter_during_normal_operating_hours_-1">
                                  Bring donations to our shelter during normal operating hours
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
